### PR TITLE
Laravel 9.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l9-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/thomasjohnkane/snooze/pull/97/commits/a1c43c1493390ba181ef3e15d28afedacefb72da?w=1) for Laravel 9. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/snooze.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "thomasjohnkane/snooze": "dev-l9-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by gerardnll** [comment]
Hi @thomasjohnkane, can you take a look at this PR now that L9 has been released? Thanks a lot.

**Comment by marcellofuschi** [comment]
@gerardnll, thumbs up for this! I have a project in production using the package and we'd like to upgrade to Laravel 9

@thomasjohnkane

**Pull request merged**
